ops:
  dates_to_extract:
    config:
      datetime_str: "%Y-%m-%dT%H:%MZ"
      archive_time_chunk: 24
      event_start: 2020-02-14T18:00Z
      event_end: 2020-02-17T18:00Z
  load_input_dataset:
    config:
      data_path: "/Users/dpeterk/data/PRd"
      dataset_filename_template: "nimrod_ng_radar_{product}_{dt.year:04d}{dt.month:02d}{dt.day:02d}.nc"
      product: rainrate_composite
