resources:
  setup:
    config:
      rainfall_thresholds:
      - 0.25
      - 2.5
      - 7.0
      - 10.0
  regrid:
    config:
      var_names:
      - radar_fraction_in_band_aggregate_3hr
      - radar_fraction_in_band_instant
      - bands_mask
      - scalar_value_mask
      - radar_max_rain_aggregate_3hr
      - radar_mean_rain_aggregate_3hr
      - radar_max_rain_instant
      - radar_mean_rain_instant
      - fraction_sum_agg
      - fraction_sum_instant
      var_types:
      - VECTOR
      - VECTOR
      - MASK_VECTOR
      - MASK_SCALAR
      - SCALAR
      - SCALAR
      - SCALAR
      - SCALAR
      - SCALAR
      - SCALAR
ops:
  dates_to_extract:
    config:
      datetime_str: "%Y-%m-%dT%H:%MZ"
      archive_time_chunk: 24
      event_start: 2020-02-14T18:00Z
      event_end: 2020-02-17T18:00Z
  load_input_dataset:
    config:
      data_path: "/Users/dpeterk/data/PRd"
      dataset_filename_template: "nimrod_ng_radar_{product}_{dt.year:04d}{dt.month:02d}{dt.day:02d}.nc"
      product: rainrate_composite
  locate_target_grid_cube:
    config:
      data_path: "/Users/dpeterk/data/PRd"
      filename: ""


# {'radar_fraction_in_band_aggregate_3hr': 'VECTOR',
# 'radar_fraction_in_band_instant': 'VECTOR',
# 'bands_mask': 'MASK_VECTOR',
# 'scalar_value_mask': 'MASK_SCALAR',
# 'radar_max_rain_aggregate_3hr': 'SCALAR',
# 'radar_mean_rain_aggregate_3hr': 'SCALAR',
# 'radar_max_rain_instant': 'SCALAR',
# 'radar_mean_rain_instant': 'SCALAR',
# 'fraction_sum_agg': 'SCALAR',
# 'fraction_sum_instant': 'SCALAR',
# }